10-wiki-page
SeattleColleges/shift-app-expo pull request #11
Opened 2024-11-09 04:40 UTC by ogarmela

This is a pull request!

Please use the following format for the title:
< repo > _ < sprint > _ < issue > _ < pr or issue name >

Please fill out this description with the following:
Resolves <issue #>
Description of what this pull request is for.
Additional information to help others that are testing.
Screenshots/gifs/videos/diagrams/other visual aids.
Remember to:
Add reviewers, assignees and labels in the menu on the right. --->
Enable auto-merge (squash) at the bottom of the page.

2024-11-10 18:49 UTC, Diego-Cano commented
This PR adds a new wiki page with documentation on development practices, naming conventions, and branching strategies for the Shift App. The wiki.md file is organized well, covering key modules like Product, Auth, and User, and gives an overview of NestJS and RESTful API principles. The diagram showing the GitFlow branching strategy is a nice touch—it really helps clarify the branching process for everyone.

One thing to adjust: the wiki page currently says "Pelletier Construction Group" even though this repository is for the Shift App. Also, updating the title to match the naming conventions (e.g., <repo>_<sprint>_<issue>_<name>) would help with consistency. Overall, this is a strong start for the documentation! For anyone interested in building out GitHub wikis effectively, here’s a good resource on [Best Practices for GitHub Wikis.](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis)

2024-11-10 18:49 UTC, Diego-Cano requested changes
One thing to adjust: the wiki page currently says "Pelletier Construction Group" even though this repository is for the Shift App.

2024-11-25 11:30 UTC, Bejarano03 commented
I looked at the files changed, and it does look like a good start. Like Diego said above, the name on the wiki is incorrect. Once that change happens this will work.

2024-11-26 00:03 UTC, miqo1385 commented
I checked the wiki and looks good to have a big picture about this project and where we are heading. good job.

2025-02-03 23:19 UTC, closed without merging

2025-02-03 23:19 UTC, IsaacJrTypes commented
Since there is no activity and the PR contains content unrelated to the Shift app, I am closing this PR