shift-app_spring-15_issue-17_Admin-Dashboard
SeattleColleges/shift-app-expo pull request #18
Opened 2024-11-25 11:21 UTC by Bejarano03

Resolves issue $17

I created the template for the admin dashboard. It still needs the logic for each button and links.

- checkout branch
- npm install modules
- npx expo start

Screen shot:

![Screenshot_1732533376](https://github.com/user-attachments/assets/85589030-121d-45ed-b0d6-6dff842f908b)

2024-11-26 04:56 UTC, nwm516 approved these changes
Great work, Marco. I was able to replicate what you created on my end and it matches the design specs that I got to you. LGTM!

![Marco PR Review](https://github.com/user-attachments/assets/c3b9ee2f-cbcf-4b9b-82f1-86d2916457f6)

2024-11-26 21:57 UTC, miqo1385 commented
it does work correctly in my end, looking good
![Screenshot 2024-11-26 at 1 57 13 PM](https://github.com/user-attachments/assets/a75526ec-0c9b-4989-94a2-406758ec931d)

2024-12-01 18:49 UTC, Diego-Cano commented
The changes introduced in this pull request adhere well to the design requirements for the admin dashboard. The placeholder profile image, greeting text, functional links for "Create Schedule" and "Review Time Off Requests," and the "Log Out" button have been implemented effectively, creating a simple and user-friendly interface. After testing the code locally, everything worked as intended and aligned with the design specifications. Moving forward, adding logic to the buttons and links will significantly enhance the dashboard's functionality.

To improve the quality of this work further, I suggest including more descriptive comments in the code for better team understanding and maintainability. For more insights on managing admin pages, here is a helpful link: [Authentication in Expo Router](https://docs.expo.dev/router/reference/authentication/)

![Screenshot 2024-12-01 at 10 43 22 AM](https://github.com/user-attachments/assets/37894e47-be24-4fc5-9fe4-bc940e07ce30)

2024-12-01 18:49 UTC, Diego-Cano approved these changes
Great Job!

2024-12-02 12:53 UTC, el-riber approved these changes

2024-12-03 23:09 UTC, IsaacJrTypes requested changes
The page looks great! Remember to include your .env file to the .gitignore file. It should be pretty easy to get new credentials.

2024-12-03 23:11 UTC, IsaacJrTypes requested changes

2024-12-03 23:11 UTC, IsaacJrTypes commented on .env
> +EXPO_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5aGNzbXhoZ2NmdnFvaHR6a3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEzOTAzODgsImV4cCI6MjA0Njk2NjM4OH0.rQsQ
You will have to get a new key since the .env file was accidentally committed.

2024-12-12 00:21 UTC, Bejarano03 commented on .env
> +EXPO_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5aGNzbXhoZ2NmdnFvaHR6a3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEzOTAzODgsImV4cCI6MjA0Njk2NjM4OH0.rQsQ
I went ahead and implemented env to git ignore. Let me know if this okay now.

2024-12-17 02:08 UTC, IsaacJrTypes approved these changes

2025-01-14 02:50 UTC, merged