shift-app-expo_sprint15_issue#20_Create-Login-Signup-page
SeattleColleges/shift-app-expo pull request #23
Opened 2024-12-01 21:12 UTC by miqo1385

Resolves issue #20 

Pull Request Description
Implemented loginpage and signuppage Components

This pull request introduces two responsive and user-friendly pages for the application: loginpage and signuppage. Both pages maintain a consistent design style and are optimized for various device sizes (phones, tablets, and web).

https://github.com/user-attachments/assets/e4905ede-d455-4296-92c8-52455db620cb

2024-12-02 13:15 UTC, el-riber approved these changes
![Screenshot_2-12-2024_61337_localhost](https://github.com/user-attachments/assets/a3786ea7-8821-4862-a3e9-3ef419a5ef65)
![Screenshot_2-12-2024_61418_localhost](https://github.com/user-attachments/assets/463e96d6-80be-4fbf-8f7f-916f9a09baf1)

working great

2024-12-03 22:57 UTC, IsaacJrTypes requested changes
Good job on creating these page! I left comments on minor changes to the PR.

2024-12-03 22:57 UTC, IsaacJrTypes commented on package.json
> +    "@supabase/supabase-js": "^2.46.1",
Lets remove the `^` symbol so we have more control on updating packages.

2024-12-03 22:57 UTC, IsaacJrTypes commented on package.json
> +    "expo": "^52.0.11",
Here

2024-12-03 22:57 UTC, IsaacJrTypes commented on package.json
> +    "expo-router": "^3.1.0",
And, this last one as well

2024-12-03 22:57 UTC, IsaacJrTypes commented on package.json
>      "expo-status-bar": "~1.12.1",
We can leave the tilde symbol (`~`) since it will only update patches.

2024-12-27 03:51 UTC, nwm516 approved these changes
LGTM, @miqo1385 ! I was able to replicate the results on mobile with an Android emulator:

![Miguel - Login Page](https://github.com/user-attachments/assets/6f5db4e7-5d8f-4169-b48e-47b7c4d0d621)
![Miguel - Signup Page](https://github.com/user-attachments/assets/943ac334-2958-4aa7-9376-4fa325c9ac84)

Thank you for creating these pages to the specifications laid out. This really helps us get the project moving in the right direction!

2025-01-19 23:02 UTC, JoyZhang2023 approved these changes
Good job! I was able to run and access both login and signup page as demo.

2025-01-20 03:59 UTC, el-riber approved these changes
it is working  !!
![Screenshot_19-1-2025_20580_localhost](https://github.com/user-attachments/assets/a7dd8bea-7df2-4b49-a8c3-6c689fd3936b)

![Screenshot_19-1-2025_205714_localhost](https://github.com/user-attachments/assets/ae8569dc-9439-459d-a66e-8065e17217d4)

2025-01-21 06:32 UTC, IsaacJrTypes approved these changes

2025-01-24 05:08 UTC, merged